name = "orifit-store"
account_id = "c96f59a4c839c1a81ece83aa4bb8269e"
workers_dev = true
main = "src/index.ts"
compatibility_date = "2025-09-27"
compatibility_flags = ["nodejs_compat"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "orifit-db"
database_id = "13b2d857-c131-4d9a-891a-dfa87d4e016f"

# R2 Bucket
[[r2_buckets]]
binding = "R2"
bucket_name = "orifit-images"
